// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: app/stock/pb/stock.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 扣减库存请求
type DeductStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockReq) Reset() {
	*x = DeductStockReq{}
	mi := &file_app_stock_pb_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockReq) ProtoMessage() {}

func (x *DeductStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_pb_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockReq.ProtoReflect.Descriptor instead.
func (*DeductStockReq) Descriptor() ([]byte, []int) {
	return file_app_stock_pb_stock_proto_rawDescGZIP(), []int{0}
}

func (x *DeductStockReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeductStockReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeductStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockResp) Reset() {
	*x = DeductStockResp{}
	mi := &file_app_stock_pb_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockResp) ProtoMessage() {}

func (x *DeductStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_pb_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockResp.ProtoReflect.Descriptor instead.
func (*DeductStockResp) Descriptor() ([]byte, []int) {
	return file_app_stock_pb_stock_proto_rawDescGZIP(), []int{1}
}

func (x *DeductStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeductStockResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 回滚库存请求
type RollbackStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackStockReq) Reset() {
	*x = RollbackStockReq{}
	mi := &file_app_stock_pb_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackStockReq) ProtoMessage() {}

func (x *RollbackStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_pb_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackStockReq.ProtoReflect.Descriptor instead.
func (*RollbackStockReq) Descriptor() ([]byte, []int) {
	return file_app_stock_pb_stock_proto_rawDescGZIP(), []int{2}
}

func (x *RollbackStockReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *RollbackStockReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RollbackStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackStockResp) Reset() {
	*x = RollbackStockResp{}
	mi := &file_app_stock_pb_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackStockResp) ProtoMessage() {}

func (x *RollbackStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_pb_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackStockResp.ProtoReflect.Descriptor instead.
func (*RollbackStockResp) Descriptor() ([]byte, []int) {
	return file_app_stock_pb_stock_proto_rawDescGZIP(), []int{3}
}

func (x *RollbackStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 查询库存请求
type GetStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockReq) Reset() {
	*x = GetStockReq{}
	mi := &file_app_stock_pb_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockReq) ProtoMessage() {}

func (x *GetStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_pb_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockReq.ProtoReflect.Descriptor instead.
func (*GetStockReq) Descriptor() ([]byte, []int) {
	return file_app_stock_pb_stock_proto_rawDescGZIP(), []int{4}
}

func (x *GetStockReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         int32                  `protobuf:"varint,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResp) Reset() {
	*x = GetStockResp{}
	mi := &file_app_stock_pb_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResp) ProtoMessage() {}

func (x *GetStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_pb_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResp.ProtoReflect.Descriptor instead.
func (*GetStockResp) Descriptor() ([]byte, []int) {
	return file_app_stock_pb_stock_proto_rawDescGZIP(), []int{5}
}

func (x *GetStockResp) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

// 批量查询库存请求
type BatchGetStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []int64                `protobuf:"varint,1,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetStockReq) Reset() {
	*x = BatchGetStockReq{}
	mi := &file_app_stock_pb_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetStockReq) ProtoMessage() {}

func (x *BatchGetStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_pb_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetStockReq.ProtoReflect.Descriptor instead.
func (*BatchGetStockReq) Descriptor() ([]byte, []int) {
	return file_app_stock_pb_stock_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetStockReq) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type BatchGetStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stocks        map[int64]int32        `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetStockResp) Reset() {
	*x = BatchGetStockResp{}
	mi := &file_app_stock_pb_stock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetStockResp) ProtoMessage() {}

func (x *BatchGetStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_pb_stock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetStockResp.ProtoReflect.Descriptor instead.
func (*BatchGetStockResp) Descriptor() ([]byte, []int) {
	return file_app_stock_pb_stock_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetStockResp) GetStocks() map[int64]int32 {
	if x != nil {
		return x.Stocks
	}
	return nil
}

var File_app_stock_pb_stock_proto protoreflect.FileDescriptor

const file_app_stock_pb_stock_proto_rawDesc = "" +
	"\n" +
	"\x18app/stock/pb/stock.proto\x12\x02pb\"E\n" +
	"\x0eDeductStockReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"E\n" +
	"\x0fDeductStockResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x10RollbackStockReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"-\n" +
	"\x11RollbackStockResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\vGetStockReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"$\n" +
	"\fGetStockResp\x12\x14\n" +
	"\x05stock\x18\x01 \x01(\x05R\x05stock\"3\n" +
	"\x10BatchGetStockReq\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\x03R\n" +
	"productIds\"\x89\x01\n" +
	"\x11BatchGetStockResp\x129\n" +
	"\x06stocks\x18\x01 \x03(\v2!.pb.BatchGetStockResp.StocksEntryR\x06stocks\x1a9\n" +
	"\vStocksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\xea\x01\n" +
	"\x05Stock\x126\n" +
	"\vDeductStock\x12\x12.pb.DeductStockReq\x1a\x13.pb.DeductStockResp\x12<\n" +
	"\rRollbackStock\x12\x14.pb.RollbackStockReq\x1a\x15.pb.RollbackStockResp\x12-\n" +
	"\bGetStock\x12\x0f.pb.GetStockReq\x1a\x10.pb.GetStockResp\x12<\n" +
	"\rBatchGetStock\x12\x14.pb.BatchGetStockReq\x1a\x15.pb.BatchGetStockRespB\x06Z\x04./pbb\x06proto3"

var (
	file_app_stock_pb_stock_proto_rawDescOnce sync.Once
	file_app_stock_pb_stock_proto_rawDescData []byte
)

func file_app_stock_pb_stock_proto_rawDescGZIP() []byte {
	file_app_stock_pb_stock_proto_rawDescOnce.Do(func() {
		file_app_stock_pb_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_stock_pb_stock_proto_rawDesc), len(file_app_stock_pb_stock_proto_rawDesc)))
	})
	return file_app_stock_pb_stock_proto_rawDescData
}

var file_app_stock_pb_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_app_stock_pb_stock_proto_goTypes = []any{
	(*DeductStockReq)(nil),    // 0: pb.DeductStockReq
	(*DeductStockResp)(nil),   // 1: pb.DeductStockResp
	(*RollbackStockReq)(nil),  // 2: pb.RollbackStockReq
	(*RollbackStockResp)(nil), // 3: pb.RollbackStockResp
	(*GetStockReq)(nil),       // 4: pb.GetStockReq
	(*GetStockResp)(nil),      // 5: pb.GetStockResp
	(*BatchGetStockReq)(nil),  // 6: pb.BatchGetStockReq
	(*BatchGetStockResp)(nil), // 7: pb.BatchGetStockResp
	nil,                       // 8: pb.BatchGetStockResp.StocksEntry
}
var file_app_stock_pb_stock_proto_depIdxs = []int32{
	8, // 0: pb.BatchGetStockResp.stocks:type_name -> pb.BatchGetStockResp.StocksEntry
	0, // 1: pb.Stock.DeductStock:input_type -> pb.DeductStockReq
	2, // 2: pb.Stock.RollbackStock:input_type -> pb.RollbackStockReq
	4, // 3: pb.Stock.GetStock:input_type -> pb.GetStockReq
	6, // 4: pb.Stock.BatchGetStock:input_type -> pb.BatchGetStockReq
	1, // 5: pb.Stock.DeductStock:output_type -> pb.DeductStockResp
	3, // 6: pb.Stock.RollbackStock:output_type -> pb.RollbackStockResp
	5, // 7: pb.Stock.GetStock:output_type -> pb.GetStockResp
	7, // 8: pb.Stock.BatchGetStock:output_type -> pb.BatchGetStockResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_stock_pb_stock_proto_init() }
func file_app_stock_pb_stock_proto_init() {
	if File_app_stock_pb_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_stock_pb_stock_proto_rawDesc), len(file_app_stock_pb_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_stock_pb_stock_proto_goTypes,
		DependencyIndexes: file_app_stock_pb_stock_proto_depIdxs,
		MessageInfos:      file_app_stock_pb_stock_proto_msgTypes,
	}.Build()
	File_app_stock_pb_stock_proto = out.File
	file_app_stock_pb_stock_proto_goTypes = nil
	file_app_stock_pb_stock_proto_depIdxs = nil
}
