// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: app/order/pb/order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建订单(下单/秒杀) 请求
type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 下单用户
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // 商品ID
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                          // 购买数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_app_order_pb_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_pb_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_app_order_pb_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`           // 返回业务订单号
	ExpireTime    int64                  `protobuf:"varint,2,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 订单过期时间（Unix时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_app_order_pb_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_pb_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_app_order_pb_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateOrderResp) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

// 支付确认请求
type ConfirmPayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`          // 订单号
	PaymentNo     string                 `protobuf:"bytes,2,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`    // 支付单号
	PayChannel    string                 `protobuf:"bytes,3,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"` // 支付渠道
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPayReq) Reset() {
	*x = ConfirmPayReq{}
	mi := &file_app_order_pb_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPayReq) ProtoMessage() {}

func (x *ConfirmPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_pb_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPayReq.ProtoReflect.Descriptor instead.
func (*ConfirmPayReq) Descriptor() ([]byte, []int) {
	return file_app_order_pb_order_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmPayReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ConfirmPayReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *ConfirmPayReq) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

type ConfirmPayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPayResp) Reset() {
	*x = ConfirmPayResp{}
	mi := &file_app_order_pb_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPayResp) ProtoMessage() {}

func (x *ConfirmPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_pb_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPayResp.ProtoReflect.Descriptor instead.
func (*ConfirmPayResp) Descriptor() ([]byte, []int) {
	return file_app_order_pb_order_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmPayResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmPayResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 订单列表请求
type ListOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户ID
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                     // 订单状态筛选 (0=待支付, 1=已支付, 2=已取消, 3=已超时)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderReq) Reset() {
	*x = ListOrderReq{}
	mi := &file_app_order_pb_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderReq) ProtoMessage() {}

func (x *ListOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_pb_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderReq.ProtoReflect.Descriptor instead.
func (*ListOrderReq) Descriptor() ([]byte, []int) {
	return file_app_order_pb_order_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrderReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrderReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrderReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderItem           `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderResp) Reset() {
	*x = ListOrderResp{}
	mi := &file_app_order_pb_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderResp) ProtoMessage() {}

func (x *ListOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_pb_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderResp.ProtoReflect.Descriptor instead.
func (*ListOrderResp) Descriptor() ([]byte, []int) {
	return file_app_order_pb_order_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrderResp) GetOrders() []*OrderItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrderResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrderResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrderResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,5,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Count         int32                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,7,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	StatusText    string                 `protobuf:"bytes,9,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	CreateTime    int64                  `protobuf:"varint,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	PayTime       int64                  `protobuf:"varint,11,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,12,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 订单过期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_app_order_pb_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_pb_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_app_order_pb_order_proto_rawDescGZIP(), []int{6}
}

func (x *OrderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OrderItem) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderItem) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *OrderItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *OrderItem) GetPayTime() int64 {
	if x != nil {
		return x.PayTime
	}
	return 0
}

func (x *OrderItem) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

// 订单详情请求
type GetOrderDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`   // 用户ID
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"` // 订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailReq) Reset() {
	*x = GetOrderDetailReq{}
	mi := &file_app_order_pb_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailReq) ProtoMessage() {}

func (x *GetOrderDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_pb_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailReq.ProtoReflect.Descriptor instead.
func (*GetOrderDetailReq) Descriptor() ([]byte, []int) {
	return file_app_order_pb_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderDetailReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderDetailReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetOrderDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,5,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductDesc   string                 `protobuf:"bytes,6,opt,name=product_desc,json=productDesc,proto3" json:"product_desc,omitempty"`
	ProductImage  string                 `protobuf:"bytes,7,opt,name=product_image,json=productImage,proto3" json:"product_image,omitempty"`
	Count         int32                  `protobuf:"varint,8,opt,name=count,proto3" json:"count,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,9,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	StatusText    string                 `protobuf:"bytes,11,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	CreateTime    int64                  `protobuf:"varint,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	PayTime       int64                  `protobuf:"varint,13,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,14,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailResp) Reset() {
	*x = GetOrderDetailResp{}
	mi := &file_app_order_pb_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailResp) ProtoMessage() {}

func (x *GetOrderDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_pb_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailResp.ProtoReflect.Descriptor instead.
func (*GetOrderDetailResp) Descriptor() ([]byte, []int) {
	return file_app_order_pb_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderDetailResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderDetailResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetOrderDetailResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderDetailResp) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetOrderDetailResp) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *GetOrderDetailResp) GetProductDesc() string {
	if x != nil {
		return x.ProductDesc
	}
	return ""
}

func (x *GetOrderDetailResp) GetProductImage() string {
	if x != nil {
		return x.ProductImage
	}
	return ""
}

func (x *GetOrderDetailResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetOrderDetailResp) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetOrderDetailResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetOrderDetailResp) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *GetOrderDetailResp) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *GetOrderDetailResp) GetPayTime() int64 {
	if x != nil {
		return x.PayTime
	}
	return 0
}

func (x *GetOrderDetailResp) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

// 取消订单请求
type CancelOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`   // 用户ID
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"` // 订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	mi := &file_app_order_pb_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_pb_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_app_order_pb_order_proto_rawDescGZIP(), []int{9}
}

func (x *CancelOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type CancelOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResp) Reset() {
	*x = CancelOrderResp{}
	mi := &file_app_order_pb_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResp) ProtoMessage() {}

func (x *CancelOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_pb_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResp.ProtoReflect.Descriptor instead.
func (*CancelOrderResp) Descriptor() ([]byte, []int) {
	return file_app_order_pb_order_proto_rawDescGZIP(), []int{10}
}

func (x *CancelOrderResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelOrderResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_app_order_pb_order_proto protoreflect.FileDescriptor

const file_app_order_pb_order_proto_rawDesc = "" +
	"\n" +
	"\x18app/order/pb/order.proto\x12\x02pb\"^\n" +
	"\x0eCreateOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"M\n" +
	"\x0fCreateOrderResp\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vexpire_time\x18\x02 \x01(\x03R\n" +
	"expireTime\"j\n" +
	"\rConfirmPayReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x02 \x01(\tR\tpaymentNo\x12\x1f\n" +
	"\vpay_channel\x18\x03 \x01(\tR\n" +
	"payChannel\"D\n" +
	"\x0eConfirmPayResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"p\n" +
	"\fListOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"}\n" +
	"\rListOrderResp\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.pb.OrderItemR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xe0\x02\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x05 \x01(\tR\vproductName\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x05R\x05count\x12!\n" +
	"\ftotal_amount\x18\a \x01(\x03R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_text\x18\t \x01(\tR\n" +
	"statusText\x12\x1f\n" +
	"\vcreate_time\x18\n" +
	" \x01(\x03R\n" +
	"createTime\x12\x19\n" +
	"\bpay_time\x18\v \x01(\x03R\apayTime\x12\x1f\n" +
	"\vexpire_time\x18\f \x01(\x03R\n" +
	"expireTime\"G\n" +
	"\x11GetOrderDetailReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\"\xb1\x03\n" +
	"\x12GetOrderDetailResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x05 \x01(\tR\vproductName\x12!\n" +
	"\fproduct_desc\x18\x06 \x01(\tR\vproductDesc\x12#\n" +
	"\rproduct_image\x18\a \x01(\tR\fproductImage\x12\x14\n" +
	"\x05count\x18\b \x01(\x05R\x05count\x12!\n" +
	"\ftotal_amount\x18\t \x01(\x03R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_text\x18\v \x01(\tR\n" +
	"statusText\x12\x1f\n" +
	"\vcreate_time\x18\f \x01(\x03R\n" +
	"createTime\x12\x19\n" +
	"\bpay_time\x18\r \x01(\x03R\apayTime\x12\x1f\n" +
	"\vexpire_time\x18\x0e \x01(\x03R\n" +
	"expireTime\"D\n" +
	"\x0eCancelOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\"E\n" +
	"\x0fCancelOrderResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9f\x02\n" +
	"\x05Order\x126\n" +
	"\vCreateOrder\x12\x12.pb.CreateOrderReq\x1a\x13.pb.CreateOrderResp\x123\n" +
	"\n" +
	"ConfirmPay\x12\x11.pb.ConfirmPayReq\x1a\x12.pb.ConfirmPayResp\x120\n" +
	"\tListOrder\x12\x10.pb.ListOrderReq\x1a\x11.pb.ListOrderResp\x12?\n" +
	"\x0eGetOrderDetail\x12\x15.pb.GetOrderDetailReq\x1a\x16.pb.GetOrderDetailResp\x126\n" +
	"\vCancelOrder\x12\x12.pb.CancelOrderReq\x1a\x13.pb.CancelOrderRespB\x06Z\x04./pbb\x06proto3"

var (
	file_app_order_pb_order_proto_rawDescOnce sync.Once
	file_app_order_pb_order_proto_rawDescData []byte
)

func file_app_order_pb_order_proto_rawDescGZIP() []byte {
	file_app_order_pb_order_proto_rawDescOnce.Do(func() {
		file_app_order_pb_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_order_pb_order_proto_rawDesc), len(file_app_order_pb_order_proto_rawDesc)))
	})
	return file_app_order_pb_order_proto_rawDescData
}

var file_app_order_pb_order_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_app_order_pb_order_proto_goTypes = []any{
	(*CreateOrderReq)(nil),     // 0: pb.CreateOrderReq
	(*CreateOrderResp)(nil),    // 1: pb.CreateOrderResp
	(*ConfirmPayReq)(nil),      // 2: pb.ConfirmPayReq
	(*ConfirmPayResp)(nil),     // 3: pb.ConfirmPayResp
	(*ListOrderReq)(nil),       // 4: pb.ListOrderReq
	(*ListOrderResp)(nil),      // 5: pb.ListOrderResp
	(*OrderItem)(nil),          // 6: pb.OrderItem
	(*GetOrderDetailReq)(nil),  // 7: pb.GetOrderDetailReq
	(*GetOrderDetailResp)(nil), // 8: pb.GetOrderDetailResp
	(*CancelOrderReq)(nil),     // 9: pb.CancelOrderReq
	(*CancelOrderResp)(nil),    // 10: pb.CancelOrderResp
}
var file_app_order_pb_order_proto_depIdxs = []int32{
	6,  // 0: pb.ListOrderResp.orders:type_name -> pb.OrderItem
	0,  // 1: pb.Order.CreateOrder:input_type -> pb.CreateOrderReq
	2,  // 2: pb.Order.ConfirmPay:input_type -> pb.ConfirmPayReq
	4,  // 3: pb.Order.ListOrder:input_type -> pb.ListOrderReq
	7,  // 4: pb.Order.GetOrderDetail:input_type -> pb.GetOrderDetailReq
	9,  // 5: pb.Order.CancelOrder:input_type -> pb.CancelOrderReq
	1,  // 6: pb.Order.CreateOrder:output_type -> pb.CreateOrderResp
	3,  // 7: pb.Order.ConfirmPay:output_type -> pb.ConfirmPayResp
	5,  // 8: pb.Order.ListOrder:output_type -> pb.ListOrderResp
	8,  // 9: pb.Order.GetOrderDetail:output_type -> pb.GetOrderDetailResp
	10, // 10: pb.Order.CancelOrder:output_type -> pb.CancelOrderResp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_app_order_pb_order_proto_init() }
func file_app_order_pb_order_proto_init() {
	if File_app_order_pb_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_order_pb_order_proto_rawDesc), len(file_app_order_pb_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_order_pb_order_proto_goTypes,
		DependencyIndexes: file_app_order_pb_order_proto_depIdxs,
		MessageInfos:      file_app_order_pb_order_proto_msgTypes,
	}.Build()
	File_app_order_pb_order_proto = out.File
	file_app_order_pb_order_proto_goTypes = nil
	file_app_order_pb_order_proto_depIdxs = nil
}
