// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: app/cart/pb/cart.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Selected      bool                   `protobuf:"varint,6,opt,name=selected,proto3" json:"selected,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CartItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CartItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CartItem) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CartItem) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *CartItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CartItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AddCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Count         int32                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartReq) Reset() {
	*x = AddCartReq{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartReq) ProtoMessage() {}

func (x *AddCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartReq.ProtoReflect.Descriptor instead.
func (*AddCartReq) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{1}
}

func (x *AddCartReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCartReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddCartReq) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *AddCartReq) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddCartReq) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *AddCartReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AddCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartResp) Reset() {
	*x = AddCartResp{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartResp) ProtoMessage() {}

func (x *AddCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartResp.ProtoReflect.Descriptor instead.
func (*AddCartResp) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{2}
}

func (x *AddCartResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddCartResp) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartReq) Reset() {
	*x = GetCartReq{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartReq) ProtoMessage() {}

func (x *GetCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartReq.ProtoReflect.Descriptor instead.
func (*GetCartReq) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{3}
}

func (x *GetCartReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResp) Reset() {
	*x = GetCartResp{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResp) ProtoMessage() {}

func (x *GetCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResp.ProtoReflect.Descriptor instead.
func (*GetCartResp) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{4}
}

func (x *GetCartResp) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCartResp) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetCartResp) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type UpdateCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartReq) Reset() {
	*x = UpdateCartReq{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartReq) ProtoMessage() {}

func (x *UpdateCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartReq.ProtoReflect.Descriptor instead.
func (*UpdateCartReq) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCartReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCartReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateCartReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartResp) Reset() {
	*x = UpdateCartResp{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartResp) ProtoMessage() {}

func (x *UpdateCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartResp.ProtoReflect.Descriptor instead.
func (*UpdateCartResp) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCartResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCartReq) Reset() {
	*x = RemoveCartReq{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCartReq) ProtoMessage() {}

func (x *RemoveCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCartReq.ProtoReflect.Descriptor instead.
func (*RemoveCartReq) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveCartReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveCartReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type RemoveCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCartResp) Reset() {
	*x = RemoveCartResp{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCartResp) ProtoMessage() {}

func (x *RemoveCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCartResp.ProtoReflect.Descriptor instead.
func (*RemoveCartResp) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveCartResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClearCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartReq) Reset() {
	*x = ClearCartReq{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartReq) ProtoMessage() {}

func (x *ClearCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartReq.ProtoReflect.Descriptor instead.
func (*ClearCartReq) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{9}
}

func (x *ClearCartReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ClearCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	RemovedCount  int32                  `protobuf:"varint,2,opt,name=removed_count,json=removedCount,proto3" json:"removed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartResp) Reset() {
	*x = ClearCartResp{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartResp) ProtoMessage() {}

func (x *ClearCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartResp.ProtoReflect.Descriptor instead.
func (*ClearCartResp) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{10}
}

func (x *ClearCartResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClearCartResp) GetRemovedCount() int32 {
	if x != nil {
		return x.RemovedCount
	}
	return 0
}

type SelectCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Selected      bool                   `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectCartReq) Reset() {
	*x = SelectCartReq{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectCartReq) ProtoMessage() {}

func (x *SelectCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectCartReq.ProtoReflect.Descriptor instead.
func (*SelectCartReq) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{11}
}

func (x *SelectCartReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SelectCartReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SelectCartReq) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

type SelectCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectCartResp) Reset() {
	*x = SelectCartResp{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectCartResp) ProtoMessage() {}

func (x *SelectCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectCartResp.ProtoReflect.Descriptor instead.
func (*SelectCartResp) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{12}
}

func (x *SelectCartResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSelectedCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSelectedCartReq) Reset() {
	*x = GetSelectedCartReq{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSelectedCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSelectedCartReq) ProtoMessage() {}

func (x *GetSelectedCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSelectedCartReq.ProtoReflect.Descriptor instead.
func (*GetSelectedCartReq) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{13}
}

func (x *GetSelectedCartReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSelectedCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	SelectedCount int32                  `protobuf:"varint,2,opt,name=selected_count,json=selectedCount,proto3" json:"selected_count,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSelectedCartResp) Reset() {
	*x = GetSelectedCartResp{}
	mi := &file_app_cart_pb_cart_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSelectedCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSelectedCartResp) ProtoMessage() {}

func (x *GetSelectedCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_cart_pb_cart_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSelectedCartResp.ProtoReflect.Descriptor instead.
func (*GetSelectedCartResp) Descriptor() ([]byte, []int) {
	return file_app_cart_pb_cart_proto_rawDescGZIP(), []int{14}
}

func (x *GetSelectedCartResp) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetSelectedCartResp) GetSelectedCount() int32 {
	if x != nil {
		return x.SelectedCount
	}
	return 0
}

func (x *GetSelectedCartResp) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

var File_app_cart_pb_cart_proto protoreflect.FileDescriptor

const file_app_cart_pb_cart_proto_rawDesc = "" +
	"\n" +
	"\x16app/cart/pb/cart.proto\x12\x02pb\"\xef\x01\n" +
	"\bCartItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12\x1a\n" +
	"\bselected\x18\x06 \x01(\bR\bselected\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xb0\x01\n" +
	"\n" +
	"AddCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x05R\x05count\"H\n" +
	"\vAddCartResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"%\n" +
	"\n" +
	"GetCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"u\n" +
	"\vGetCartResp\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.pb.CartItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\"]\n" +
	"\rUpdateCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"*\n" +
	"\x0eUpdateCartResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"G\n" +
	"\rRemoveCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\"*\n" +
	"\x0eRemoveCartResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\fClearCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"N\n" +
	"\rClearCartResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12#\n" +
	"\rremoved_count\x18\x02 \x01(\x05R\fremovedCount\"c\n" +
	"\rSelectCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bselected\x18\x03 \x01(\bR\bselected\"*\n" +
	"\x0eSelectCartResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"-\n" +
	"\x12GetSelectedCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x83\x01\n" +
	"\x13GetSelectedCartResp\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.pb.CartItemR\x05items\x12%\n" +
	"\x0eselected_count\x18\x02 \x01(\x05R\rselectedCount\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount2\xf3\x02\n" +
	"\x04Cart\x12*\n" +
	"\aAddCart\x12\x0e.pb.AddCartReq\x1a\x0f.pb.AddCartResp\x12*\n" +
	"\aGetCart\x12\x0e.pb.GetCartReq\x1a\x0f.pb.GetCartResp\x123\n" +
	"\n" +
	"UpdateCart\x12\x11.pb.UpdateCartReq\x1a\x12.pb.UpdateCartResp\x123\n" +
	"\n" +
	"RemoveCart\x12\x11.pb.RemoveCartReq\x1a\x12.pb.RemoveCartResp\x120\n" +
	"\tClearCart\x12\x10.pb.ClearCartReq\x1a\x11.pb.ClearCartResp\x123\n" +
	"\n" +
	"SelectCart\x12\x11.pb.SelectCartReq\x1a\x12.pb.SelectCartResp\x12B\n" +
	"\x0fGetSelectedCart\x12\x16.pb.GetSelectedCartReq\x1a\x17.pb.GetSelectedCartRespB\x06Z\x04./pbb\x06proto3"

var (
	file_app_cart_pb_cart_proto_rawDescOnce sync.Once
	file_app_cart_pb_cart_proto_rawDescData []byte
)

func file_app_cart_pb_cart_proto_rawDescGZIP() []byte {
	file_app_cart_pb_cart_proto_rawDescOnce.Do(func() {
		file_app_cart_pb_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_cart_pb_cart_proto_rawDesc), len(file_app_cart_pb_cart_proto_rawDesc)))
	})
	return file_app_cart_pb_cart_proto_rawDescData
}

var file_app_cart_pb_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_app_cart_pb_cart_proto_goTypes = []any{
	(*CartItem)(nil),            // 0: pb.CartItem
	(*AddCartReq)(nil),          // 1: pb.AddCartReq
	(*AddCartResp)(nil),         // 2: pb.AddCartResp
	(*GetCartReq)(nil),          // 3: pb.GetCartReq
	(*GetCartResp)(nil),         // 4: pb.GetCartResp
	(*UpdateCartReq)(nil),       // 5: pb.UpdateCartReq
	(*UpdateCartResp)(nil),      // 6: pb.UpdateCartResp
	(*RemoveCartReq)(nil),       // 7: pb.RemoveCartReq
	(*RemoveCartResp)(nil),      // 8: pb.RemoveCartResp
	(*ClearCartReq)(nil),        // 9: pb.ClearCartReq
	(*ClearCartResp)(nil),       // 10: pb.ClearCartResp
	(*SelectCartReq)(nil),       // 11: pb.SelectCartReq
	(*SelectCartResp)(nil),      // 12: pb.SelectCartResp
	(*GetSelectedCartReq)(nil),  // 13: pb.GetSelectedCartReq
	(*GetSelectedCartResp)(nil), // 14: pb.GetSelectedCartResp
}
var file_app_cart_pb_cart_proto_depIdxs = []int32{
	0,  // 0: pb.GetCartResp.items:type_name -> pb.CartItem
	0,  // 1: pb.GetSelectedCartResp.items:type_name -> pb.CartItem
	1,  // 2: pb.Cart.AddCart:input_type -> pb.AddCartReq
	3,  // 3: pb.Cart.GetCart:input_type -> pb.GetCartReq
	5,  // 4: pb.Cart.UpdateCart:input_type -> pb.UpdateCartReq
	7,  // 5: pb.Cart.RemoveCart:input_type -> pb.RemoveCartReq
	9,  // 6: pb.Cart.ClearCart:input_type -> pb.ClearCartReq
	11, // 7: pb.Cart.SelectCart:input_type -> pb.SelectCartReq
	13, // 8: pb.Cart.GetSelectedCart:input_type -> pb.GetSelectedCartReq
	2,  // 9: pb.Cart.AddCart:output_type -> pb.AddCartResp
	4,  // 10: pb.Cart.GetCart:output_type -> pb.GetCartResp
	6,  // 11: pb.Cart.UpdateCart:output_type -> pb.UpdateCartResp
	8,  // 12: pb.Cart.RemoveCart:output_type -> pb.RemoveCartResp
	10, // 13: pb.Cart.ClearCart:output_type -> pb.ClearCartResp
	12, // 14: pb.Cart.SelectCart:output_type -> pb.SelectCartResp
	14, // 15: pb.Cart.GetSelectedCart:output_type -> pb.GetSelectedCartResp
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_app_cart_pb_cart_proto_init() }
func file_app_cart_pb_cart_proto_init() {
	if File_app_cart_pb_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_cart_pb_cart_proto_rawDesc), len(file_app_cart_pb_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_cart_pb_cart_proto_goTypes,
		DependencyIndexes: file_app_cart_pb_cart_proto_depIdxs,
		MessageInfos:      file_app_cart_pb_cart_proto_msgTypes,
	}.Build()
	File_app_cart_pb_cart_proto = out.File
	file_app_cart_pb_cart_proto_goTypes = nil
	file_app_cart_pb_cart_proto_depIdxs = nil
}
