// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: app/payment/pb/payment.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Payment_CreatePay_FullMethodName       = "/pb.Payment/CreatePay"
	Payment_GetPayStatus_FullMethodName    = "/pb.Payment/GetPayStatus"
	Payment_CancelPay_FullMethodName       = "/pb.Payment/CancelPay"
	Payment_PayCallback_FullMethodName     = "/pb.Payment/PayCallback"
	Payment_ListPay_FullMethodName         = "/pb.Payment/ListPay"
	Payment_CloseExpiredPay_FullMethodName = "/pb.Payment/CloseExpiredPay"
)

// PaymentClient is the client API for Payment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentClient interface {
	CreatePay(ctx context.Context, in *CreatePayReq, opts ...grpc.CallOption) (*CreatePayResp, error)
	GetPayStatus(ctx context.Context, in *GetPayStatusReq, opts ...grpc.CallOption) (*GetPayStatusResp, error)
	CancelPay(ctx context.Context, in *CancelPayReq, opts ...grpc.CallOption) (*CancelPayResp, error)
	PayCallback(ctx context.Context, in *PayCallbackReq, opts ...grpc.CallOption) (*PayCallbackResp, error)
	ListPay(ctx context.Context, in *ListPayReq, opts ...grpc.CallOption) (*ListPayResp, error)
	CloseExpiredPay(ctx context.Context, in *CloseExpiredPayReq, opts ...grpc.CallOption) (*CloseExpiredPayResp, error)
}

type paymentClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentClient(cc grpc.ClientConnInterface) PaymentClient {
	return &paymentClient{cc}
}

func (c *paymentClient) CreatePay(ctx context.Context, in *CreatePayReq, opts ...grpc.CallOption) (*CreatePayResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePayResp)
	err := c.cc.Invoke(ctx, Payment_CreatePay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) GetPayStatus(ctx context.Context, in *GetPayStatusReq, opts ...grpc.CallOption) (*GetPayStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayStatusResp)
	err := c.cc.Invoke(ctx, Payment_GetPayStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) CancelPay(ctx context.Context, in *CancelPayReq, opts ...grpc.CallOption) (*CancelPayResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPayResp)
	err := c.cc.Invoke(ctx, Payment_CancelPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) PayCallback(ctx context.Context, in *PayCallbackReq, opts ...grpc.CallOption) (*PayCallbackResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayCallbackResp)
	err := c.cc.Invoke(ctx, Payment_PayCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) ListPay(ctx context.Context, in *ListPayReq, opts ...grpc.CallOption) (*ListPayResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPayResp)
	err := c.cc.Invoke(ctx, Payment_ListPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) CloseExpiredPay(ctx context.Context, in *CloseExpiredPayReq, opts ...grpc.CallOption) (*CloseExpiredPayResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseExpiredPayResp)
	err := c.cc.Invoke(ctx, Payment_CloseExpiredPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServer is the server API for Payment service.
// All implementations must embed UnimplementedPaymentServer
// for forward compatibility.
type PaymentServer interface {
	CreatePay(context.Context, *CreatePayReq) (*CreatePayResp, error)
	GetPayStatus(context.Context, *GetPayStatusReq) (*GetPayStatusResp, error)
	CancelPay(context.Context, *CancelPayReq) (*CancelPayResp, error)
	PayCallback(context.Context, *PayCallbackReq) (*PayCallbackResp, error)
	ListPay(context.Context, *ListPayReq) (*ListPayResp, error)
	CloseExpiredPay(context.Context, *CloseExpiredPayReq) (*CloseExpiredPayResp, error)
	mustEmbedUnimplementedPaymentServer()
}

// UnimplementedPaymentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServer struct{}

func (UnimplementedPaymentServer) CreatePay(context.Context, *CreatePayReq) (*CreatePayResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePay not implemented")
}
func (UnimplementedPaymentServer) GetPayStatus(context.Context, *GetPayStatusReq) (*GetPayStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayStatus not implemented")
}
func (UnimplementedPaymentServer) CancelPay(context.Context, *CancelPayReq) (*CancelPayResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelPay not implemented")
}
func (UnimplementedPaymentServer) PayCallback(context.Context, *PayCallbackReq) (*PayCallbackResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PayCallback not implemented")
}
func (UnimplementedPaymentServer) ListPay(context.Context, *ListPayReq) (*ListPayResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPay not implemented")
}
func (UnimplementedPaymentServer) CloseExpiredPay(context.Context, *CloseExpiredPayReq) (*CloseExpiredPayResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseExpiredPay not implemented")
}
func (UnimplementedPaymentServer) mustEmbedUnimplementedPaymentServer() {}
func (UnimplementedPaymentServer) testEmbeddedByValue()                 {}

// UnsafePaymentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServer will
// result in compilation errors.
type UnsafePaymentServer interface {
	mustEmbedUnimplementedPaymentServer()
}

func RegisterPaymentServer(s grpc.ServiceRegistrar, srv PaymentServer) {
	// If the following call panics, it indicates UnimplementedPaymentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Payment_ServiceDesc, srv)
}

func _Payment_CreatePay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).CreatePay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_CreatePay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).CreatePay(ctx, req.(*CreatePayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_GetPayStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).GetPayStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_GetPayStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).GetPayStatus(ctx, req.(*GetPayStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_CancelPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).CancelPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_CancelPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).CancelPay(ctx, req.(*CancelPayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_PayCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).PayCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_PayCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).PayCallback(ctx, req.(*PayCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_ListPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).ListPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_ListPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).ListPay(ctx, req.(*ListPayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_CloseExpiredPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseExpiredPayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).CloseExpiredPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_CloseExpiredPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).CloseExpiredPay(ctx, req.(*CloseExpiredPayReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Payment_ServiceDesc is the grpc.ServiceDesc for Payment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Payment",
	HandlerType: (*PaymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePay",
			Handler:    _Payment_CreatePay_Handler,
		},
		{
			MethodName: "GetPayStatus",
			Handler:    _Payment_GetPayStatus_Handler,
		},
		{
			MethodName: "CancelPay",
			Handler:    _Payment_CancelPay_Handler,
		},
		{
			MethodName: "PayCallback",
			Handler:    _Payment_PayCallback_Handler,
		},
		{
			MethodName: "ListPay",
			Handler:    _Payment_ListPay_Handler,
		},
		{
			MethodName: "CloseExpiredPay",
			Handler:    _Payment_CloseExpiredPay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/payment/pb/payment.proto",
}
