// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: app/payment/pb/payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付记录
type PaymentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentNo     string                 `protobuf:"bytes,2,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	OrderNo       string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	StatusText    string                 `protobuf:"bytes,7,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	PayChannel    string                 `protobuf:"bytes,8,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`
	PayTime       int64                  `protobuf:"varint,9,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,10,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	mi := &file_app_payment_pb_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_payment_pb_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_app_payment_pb_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentInfo) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *PaymentInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PaymentInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PaymentInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PaymentInfo) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *PaymentInfo) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *PaymentInfo) GetPayTime() int64 {
	if x != nil {
		return x.PayTime
	}
	return 0
}

func (x *PaymentInfo) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *PaymentInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PaymentInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 发起支付
type CreatePayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PayChannel    string                 `protobuf:"bytes,4,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"` // alipay / wechat
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePayReq) Reset() {
	*x = CreatePayReq{}
	mi := &file_app_payment_pb_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePayReq) ProtoMessage() {}

func (x *CreatePayReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_payment_pb_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePayReq.ProtoReflect.Descriptor instead.
func (*CreatePayReq) Descriptor() ([]byte, []int) {
	return file_app_payment_pb_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePayReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreatePayReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePayReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePayReq) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

type CreatePayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	QrCode        string                 `protobuf:"bytes,2,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`              // 支付二维码链接
	ExpireTime    int64                  `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 过期时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePayResp) Reset() {
	*x = CreatePayResp{}
	mi := &file_app_payment_pb_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePayResp) ProtoMessage() {}

func (x *CreatePayResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_payment_pb_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePayResp.ProtoReflect.Descriptor instead.
func (*CreatePayResp) Descriptor() ([]byte, []int) {
	return file_app_payment_pb_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePayResp) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *CreatePayResp) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

func (x *CreatePayResp) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

// 查询支付状态
type GetPayStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayStatusReq) Reset() {
	*x = GetPayStatusReq{}
	mi := &file_app_payment_pb_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayStatusReq) ProtoMessage() {}

func (x *GetPayStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_payment_pb_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayStatusReq.ProtoReflect.Descriptor instead.
func (*GetPayStatusReq) Descriptor() ([]byte, []int) {
	return file_app_payment_pb_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetPayStatusReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *GetPayStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetPayStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 0待支付 1已支付 2已取消 3已超时
	StatusText    string                 `protobuf:"bytes,3,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	OrderNo       string                 `protobuf:"bytes,5,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayStatusResp) Reset() {
	*x = GetPayStatusResp{}
	mi := &file_app_payment_pb_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayStatusResp) ProtoMessage() {}

func (x *GetPayStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_payment_pb_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayStatusResp.ProtoReflect.Descriptor instead.
func (*GetPayStatusResp) Descriptor() ([]byte, []int) {
	return file_app_payment_pb_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPayStatusResp) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *GetPayStatusResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetPayStatusResp) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *GetPayStatusResp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetPayStatusResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

// 取消支付
type CancelPayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPayReq) Reset() {
	*x = CancelPayReq{}
	mi := &file_app_payment_pb_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPayReq) ProtoMessage() {}

func (x *CancelPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_payment_pb_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPayReq.ProtoReflect.Descriptor instead.
func (*CancelPayReq) Descriptor() ([]byte, []int) {
	return file_app_payment_pb_payment_proto_rawDescGZIP(), []int{5}
}

func (x *CancelPayReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *CancelPayReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CancelPayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPayResp) Reset() {
	*x = CancelPayResp{}
	mi := &file_app_payment_pb_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPayResp) ProtoMessage() {}

func (x *CancelPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_payment_pb_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPayResp.ProtoReflect.Descriptor instead.
func (*CancelPayResp) Descriptor() ([]byte, []int) {
	return file_app_payment_pb_payment_proto_rawDescGZIP(), []int{6}
}

func (x *CancelPayResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 支付回调 (内部服务调用)
type PayCallbackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	PayChannel    string                 `protobuf:"bytes,2,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`
	CallbackData  string                 `protobuf:"bytes,3,opt,name=callback_data,json=callbackData,proto3" json:"callback_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayCallbackReq) Reset() {
	*x = PayCallbackReq{}
	mi := &file_app_payment_pb_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCallbackReq) ProtoMessage() {}

func (x *PayCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_payment_pb_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCallbackReq.ProtoReflect.Descriptor instead.
func (*PayCallbackReq) Descriptor() ([]byte, []int) {
	return file_app_payment_pb_payment_proto_rawDescGZIP(), []int{7}
}

func (x *PayCallbackReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *PayCallbackReq) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *PayCallbackReq) GetCallbackData() string {
	if x != nil {
		return x.CallbackData
	}
	return ""
}

type PayCallbackResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayCallbackResp) Reset() {
	*x = PayCallbackResp{}
	mi := &file_app_payment_pb_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCallbackResp) ProtoMessage() {}

func (x *PayCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_payment_pb_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCallbackResp.ProtoReflect.Descriptor instead.
func (*PayCallbackResp) Descriptor() ([]byte, []int) {
	return file_app_payment_pb_payment_proto_rawDescGZIP(), []int{8}
}

func (x *PayCallbackResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PayCallbackResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 支付记录列表
type ListPayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPayReq) Reset() {
	*x = ListPayReq{}
	mi := &file_app_payment_pb_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPayReq) ProtoMessage() {}

func (x *ListPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_payment_pb_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPayReq.ProtoReflect.Descriptor instead.
func (*ListPayReq) Descriptor() ([]byte, []int) {
	return file_app_payment_pb_payment_proto_rawDescGZIP(), []int{9}
}

func (x *ListPayReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListPayReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPayReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*PaymentInfo         `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPayResp) Reset() {
	*x = ListPayResp{}
	mi := &file_app_payment_pb_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPayResp) ProtoMessage() {}

func (x *ListPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_payment_pb_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPayResp.ProtoReflect.Descriptor instead.
func (*ListPayResp) Descriptor() ([]byte, []int) {
	return file_app_payment_pb_payment_proto_rawDescGZIP(), []int{10}
}

func (x *ListPayResp) GetPayments() []*PaymentInfo {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ListPayResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPayResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPayResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 关闭超时支付 (内部定时任务调用)
type CloseExpiredPayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseExpiredPayReq) Reset() {
	*x = CloseExpiredPayReq{}
	mi := &file_app_payment_pb_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseExpiredPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseExpiredPayReq) ProtoMessage() {}

func (x *CloseExpiredPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_payment_pb_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseExpiredPayReq.ProtoReflect.Descriptor instead.
func (*CloseExpiredPayReq) Descriptor() ([]byte, []int) {
	return file_app_payment_pb_payment_proto_rawDescGZIP(), []int{11}
}

type CloseExpiredPayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClosedCount   int32                  `protobuf:"varint,1,opt,name=closed_count,json=closedCount,proto3" json:"closed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseExpiredPayResp) Reset() {
	*x = CloseExpiredPayResp{}
	mi := &file_app_payment_pb_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseExpiredPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseExpiredPayResp) ProtoMessage() {}

func (x *CloseExpiredPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_payment_pb_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseExpiredPayResp.ProtoReflect.Descriptor instead.
func (*CloseExpiredPayResp) Descriptor() ([]byte, []int) {
	return file_app_payment_pb_payment_proto_rawDescGZIP(), []int{12}
}

func (x *CloseExpiredPayResp) GetClosedCount() int32 {
	if x != nil {
		return x.ClosedCount
	}
	return 0
}

var File_app_payment_pb_payment_proto protoreflect.FileDescriptor

const file_app_payment_pb_payment_proto_rawDesc = "" +
	"\n" +
	"\x1capp/payment/pb/payment.proto\x12\x02pb\"\xdc\x02\n" +
	"\vPaymentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x02 \x01(\tR\tpaymentNo\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_text\x18\a \x01(\tR\n" +
	"statusText\x12\x1f\n" +
	"\vpay_channel\x18\b \x01(\tR\n" +
	"payChannel\x12\x19\n" +
	"\bpay_time\x18\t \x01(\x03R\apayTime\x12\x1f\n" +
	"\vexpire_time\x18\n" +
	" \x01(\x03R\n" +
	"expireTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\"{\n" +
	"\fCreatePayReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1f\n" +
	"\vpay_channel\x18\x04 \x01(\tR\n" +
	"payChannel\"h\n" +
	"\rCreatePayResp\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12\x17\n" +
	"\aqr_code\x18\x02 \x01(\tR\x06qrCode\x12\x1f\n" +
	"\vexpire_time\x18\x03 \x01(\x03R\n" +
	"expireTime\"I\n" +
	"\x0fGetPayStatusReq\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x9d\x01\n" +
	"\x10GetPayStatusResp\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_text\x18\x03 \x01(\tR\n" +
	"statusText\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x19\n" +
	"\border_no\x18\x05 \x01(\tR\aorderNo\"F\n" +
	"\fCancelPayReq\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\")\n" +
	"\rCancelPayResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"u\n" +
	"\x0ePayCallbackReq\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12\x1f\n" +
	"\vpay_channel\x18\x02 \x01(\tR\n" +
	"payChannel\x12#\n" +
	"\rcallback_data\x18\x03 \x01(\tR\fcallbackData\"E\n" +
	"\x0fPayCallbackResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\n" +
	"ListPayReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x81\x01\n" +
	"\vListPayResp\x12+\n" +
	"\bpayments\x18\x01 \x03(\v2\x0f.pb.PaymentInfoR\bpayments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x14\n" +
	"\x12CloseExpiredPayReq\"8\n" +
	"\x13CloseExpiredPayResp\x12!\n" +
	"\fclosed_count\x18\x01 \x01(\x05R\vclosedCount2\xd0\x02\n" +
	"\aPayment\x120\n" +
	"\tCreatePay\x12\x10.pb.CreatePayReq\x1a\x11.pb.CreatePayResp\x129\n" +
	"\fGetPayStatus\x12\x13.pb.GetPayStatusReq\x1a\x14.pb.GetPayStatusResp\x120\n" +
	"\tCancelPay\x12\x10.pb.CancelPayReq\x1a\x11.pb.CancelPayResp\x126\n" +
	"\vPayCallback\x12\x12.pb.PayCallbackReq\x1a\x13.pb.PayCallbackResp\x12*\n" +
	"\aListPay\x12\x0e.pb.ListPayReq\x1a\x0f.pb.ListPayResp\x12B\n" +
	"\x0fCloseExpiredPay\x12\x16.pb.CloseExpiredPayReq\x1a\x17.pb.CloseExpiredPayRespB\x06Z\x04./pbb\x06proto3"

var (
	file_app_payment_pb_payment_proto_rawDescOnce sync.Once
	file_app_payment_pb_payment_proto_rawDescData []byte
)

func file_app_payment_pb_payment_proto_rawDescGZIP() []byte {
	file_app_payment_pb_payment_proto_rawDescOnce.Do(func() {
		file_app_payment_pb_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_payment_pb_payment_proto_rawDesc), len(file_app_payment_pb_payment_proto_rawDesc)))
	})
	return file_app_payment_pb_payment_proto_rawDescData
}

var file_app_payment_pb_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_app_payment_pb_payment_proto_goTypes = []any{
	(*PaymentInfo)(nil),         // 0: pb.PaymentInfo
	(*CreatePayReq)(nil),        // 1: pb.CreatePayReq
	(*CreatePayResp)(nil),       // 2: pb.CreatePayResp
	(*GetPayStatusReq)(nil),     // 3: pb.GetPayStatusReq
	(*GetPayStatusResp)(nil),    // 4: pb.GetPayStatusResp
	(*CancelPayReq)(nil),        // 5: pb.CancelPayReq
	(*CancelPayResp)(nil),       // 6: pb.CancelPayResp
	(*PayCallbackReq)(nil),      // 7: pb.PayCallbackReq
	(*PayCallbackResp)(nil),     // 8: pb.PayCallbackResp
	(*ListPayReq)(nil),          // 9: pb.ListPayReq
	(*ListPayResp)(nil),         // 10: pb.ListPayResp
	(*CloseExpiredPayReq)(nil),  // 11: pb.CloseExpiredPayReq
	(*CloseExpiredPayResp)(nil), // 12: pb.CloseExpiredPayResp
}
var file_app_payment_pb_payment_proto_depIdxs = []int32{
	0,  // 0: pb.ListPayResp.payments:type_name -> pb.PaymentInfo
	1,  // 1: pb.Payment.CreatePay:input_type -> pb.CreatePayReq
	3,  // 2: pb.Payment.GetPayStatus:input_type -> pb.GetPayStatusReq
	5,  // 3: pb.Payment.CancelPay:input_type -> pb.CancelPayReq
	7,  // 4: pb.Payment.PayCallback:input_type -> pb.PayCallbackReq
	9,  // 5: pb.Payment.ListPay:input_type -> pb.ListPayReq
	11, // 6: pb.Payment.CloseExpiredPay:input_type -> pb.CloseExpiredPayReq
	2,  // 7: pb.Payment.CreatePay:output_type -> pb.CreatePayResp
	4,  // 8: pb.Payment.GetPayStatus:output_type -> pb.GetPayStatusResp
	6,  // 9: pb.Payment.CancelPay:output_type -> pb.CancelPayResp
	8,  // 10: pb.Payment.PayCallback:output_type -> pb.PayCallbackResp
	10, // 11: pb.Payment.ListPay:output_type -> pb.ListPayResp
	12, // 12: pb.Payment.CloseExpiredPay:output_type -> pb.CloseExpiredPayResp
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_app_payment_pb_payment_proto_init() }
func file_app_payment_pb_payment_proto_init() {
	if File_app_payment_pb_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_payment_pb_payment_proto_rawDesc), len(file_app_payment_pb_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_payment_pb_payment_proto_goTypes,
		DependencyIndexes: file_app_payment_pb_payment_proto_depIdxs,
		MessageInfos:      file_app_payment_pb_payment_proto_msgTypes,
	}.Build()
	File_app_payment_pb_payment_proto = out.File
	file_app_payment_pb_payment_proto_goTypes = nil
	file_app_payment_pb_payment_proto_depIdxs = nil
}
