// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: app/address/pb/address.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReceiverName  string                 `protobuf:"bytes,3,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Province      string                 `protobuf:"bytes,5,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,7,opt,name=district,proto3" json:"district,omitempty"`
	DetailAddress string                 `protobuf:"bytes,8,opt,name=detail_address,json=detailAddress,proto3" json:"detail_address,omitempty"`
	PostalCode    string                 `protobuf:"bytes,9,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	IsDefault     bool                   `protobuf:"varint,10,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressItem) Reset() {
	*x = AddressItem{}
	mi := &file_app_address_pb_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressItem) ProtoMessage() {}

func (x *AddressItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_address_pb_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressItem.ProtoReflect.Descriptor instead.
func (*AddressItem) Descriptor() ([]byte, []int) {
	return file_app_address_pb_address_proto_rawDescGZIP(), []int{0}
}

func (x *AddressItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddressItem) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *AddressItem) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AddressItem) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddressItem) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressItem) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AddressItem) GetDetailAddress() string {
	if x != nil {
		return x.DetailAddress
	}
	return ""
}

func (x *AddressItem) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *AddressItem) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type GetAddressListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressListReq) Reset() {
	*x = GetAddressListReq{}
	mi := &file_app_address_pb_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressListReq) ProtoMessage() {}

func (x *GetAddressListReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_address_pb_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressListReq.ProtoReflect.Descriptor instead.
func (*GetAddressListReq) Descriptor() ([]byte, []int) {
	return file_app_address_pb_address_proto_rawDescGZIP(), []int{1}
}

func (x *GetAddressListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetAddressListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*AddressItem         `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressListResp) Reset() {
	*x = GetAddressListResp{}
	mi := &file_app_address_pb_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressListResp) ProtoMessage() {}

func (x *GetAddressListResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_address_pb_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressListResp.ProtoReflect.Descriptor instead.
func (*GetAddressListResp) Descriptor() ([]byte, []int) {
	return file_app_address_pb_address_proto_rawDescGZIP(), []int{2}
}

func (x *GetAddressListResp) GetAddresses() []*AddressItem {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type AddAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReceiverName  string                 `protobuf:"bytes,2,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Province      string                 `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,6,opt,name=district,proto3" json:"district,omitempty"`
	DetailAddress string                 `protobuf:"bytes,7,opt,name=detail_address,json=detailAddress,proto3" json:"detail_address,omitempty"`
	PostalCode    string                 `protobuf:"bytes,8,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	IsDefault     bool                   `protobuf:"varint,9,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAddressReq) Reset() {
	*x = AddAddressReq{}
	mi := &file_app_address_pb_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAddressReq) ProtoMessage() {}

func (x *AddAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_address_pb_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAddressReq.ProtoReflect.Descriptor instead.
func (*AddAddressReq) Descriptor() ([]byte, []int) {
	return file_app_address_pb_address_proto_rawDescGZIP(), []int{3}
}

func (x *AddAddressReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddAddressReq) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *AddAddressReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AddAddressReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddAddressReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddAddressReq) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AddAddressReq) GetDetailAddress() string {
	if x != nil {
		return x.DetailAddress
	}
	return ""
}

func (x *AddAddressReq) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *AddAddressReq) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type AddAddressResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAddressResp) Reset() {
	*x = AddAddressResp{}
	mi := &file_app_address_pb_address_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAddressResp) ProtoMessage() {}

func (x *AddAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_address_pb_address_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAddressResp.ProtoReflect.Descriptor instead.
func (*AddAddressResp) Descriptor() ([]byte, []int) {
	return file_app_address_pb_address_proto_rawDescGZIP(), []int{4}
}

func (x *AddAddressResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddAddressResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddAddressResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReceiverName  string                 `protobuf:"bytes,3,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Province      string                 `protobuf:"bytes,5,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,7,opt,name=district,proto3" json:"district,omitempty"`
	DetailAddress string                 `protobuf:"bytes,8,opt,name=detail_address,json=detailAddress,proto3" json:"detail_address,omitempty"`
	PostalCode    string                 `protobuf:"bytes,9,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	IsDefault     bool                   `protobuf:"varint,10,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressReq) Reset() {
	*x = UpdateAddressReq{}
	mi := &file_app_address_pb_address_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressReq) ProtoMessage() {}

func (x *UpdateAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_address_pb_address_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressReq.ProtoReflect.Descriptor instead.
func (*UpdateAddressReq) Descriptor() ([]byte, []int) {
	return file_app_address_pb_address_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAddressReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAddressReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateAddressReq) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *UpdateAddressReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateAddressReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UpdateAddressReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateAddressReq) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UpdateAddressReq) GetDetailAddress() string {
	if x != nil {
		return x.DetailAddress
	}
	return ""
}

func (x *UpdateAddressReq) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *UpdateAddressReq) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type UpdateAddressResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressResp) Reset() {
	*x = UpdateAddressResp{}
	mi := &file_app_address_pb_address_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressResp) ProtoMessage() {}

func (x *UpdateAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_address_pb_address_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressResp.ProtoReflect.Descriptor instead.
func (*UpdateAddressResp) Descriptor() ([]byte, []int) {
	return file_app_address_pb_address_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAddressResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateAddressResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressReq) Reset() {
	*x = DeleteAddressReq{}
	mi := &file_app_address_pb_address_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressReq) ProtoMessage() {}

func (x *DeleteAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_address_pb_address_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressReq.ProtoReflect.Descriptor instead.
func (*DeleteAddressReq) Descriptor() ([]byte, []int) {
	return file_app_address_pb_address_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAddressReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteAddressReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteAddressResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressResp) Reset() {
	*x = DeleteAddressResp{}
	mi := &file_app_address_pb_address_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressResp) ProtoMessage() {}

func (x *DeleteAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_address_pb_address_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressResp.ProtoReflect.Descriptor instead.
func (*DeleteAddressResp) Descriptor() ([]byte, []int) {
	return file_app_address_pb_address_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAddressResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteAddressResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetDefaultAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultAddressReq) Reset() {
	*x = SetDefaultAddressReq{}
	mi := &file_app_address_pb_address_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultAddressReq) ProtoMessage() {}

func (x *SetDefaultAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_address_pb_address_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultAddressReq.ProtoReflect.Descriptor instead.
func (*SetDefaultAddressReq) Descriptor() ([]byte, []int) {
	return file_app_address_pb_address_proto_rawDescGZIP(), []int{9}
}

func (x *SetDefaultAddressReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetDefaultAddressReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SetDefaultAddressResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultAddressResp) Reset() {
	*x = SetDefaultAddressResp{}
	mi := &file_app_address_pb_address_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultAddressResp) ProtoMessage() {}

func (x *SetDefaultAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_address_pb_address_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultAddressResp.ProtoReflect.Descriptor instead.
func (*SetDefaultAddressResp) Descriptor() ([]byte, []int) {
	return file_app_address_pb_address_proto_rawDescGZIP(), []int{10}
}

func (x *SetDefaultAddressResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDefaultAddressResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_app_address_pb_address_proto protoreflect.FileDescriptor

const file_app_address_pb_address_proto_rawDesc = "" +
	"\n" +
	"\x1capp/address/pb/address.proto\x12\x02pb\"\xa4\x02\n" +
	"\vAddressItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12#\n" +
	"\rreceiver_name\x18\x03 \x01(\tR\freceiverName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1a\n" +
	"\bprovince\x18\x05 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\a \x01(\tR\bdistrict\x12%\n" +
	"\x0edetail_address\x18\b \x01(\tR\rdetailAddress\x12\x1f\n" +
	"\vpostal_code\x18\t \x01(\tR\n" +
	"postalCode\x12\x1d\n" +
	"\n" +
	"is_default\x18\n" +
	" \x01(\bR\tisDefault\",\n" +
	"\x11GetAddressListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"C\n" +
	"\x12GetAddressListResp\x12-\n" +
	"\taddresses\x18\x01 \x03(\v2\x0f.pb.AddressItemR\taddresses\"\x96\x02\n" +
	"\rAddAddressReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rreceiver_name\x18\x02 \x01(\tR\freceiverName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bprovince\x18\x04 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x06 \x01(\tR\bdistrict\x12%\n" +
	"\x0edetail_address\x18\a \x01(\tR\rdetailAddress\x12\x1f\n" +
	"\vpostal_code\x18\b \x01(\tR\n" +
	"postalCode\x12\x1d\n" +
	"\n" +
	"is_default\x18\t \x01(\bR\tisDefault\"T\n" +
	"\x0eAddAddressResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa9\x02\n" +
	"\x10UpdateAddressReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12#\n" +
	"\rreceiver_name\x18\x03 \x01(\tR\freceiverName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1a\n" +
	"\bprovince\x18\x05 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\a \x01(\tR\bdistrict\x12%\n" +
	"\x0edetail_address\x18\b \x01(\tR\rdetailAddress\x12\x1f\n" +
	"\vpostal_code\x18\t \x01(\tR\n" +
	"postalCode\x12\x1d\n" +
	"\n" +
	"is_default\x18\n" +
	" \x01(\bR\tisDefault\"G\n" +
	"\x11UpdateAddressResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x10DeleteAddressReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"G\n" +
	"\x11DeleteAddressResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\x14SetDefaultAddressReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"K\n" +
	"\x15SetDefaultAddressResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc5\x02\n" +
	"\aAddress\x12?\n" +
	"\x0eGetAddressList\x12\x15.pb.GetAddressListReq\x1a\x16.pb.GetAddressListResp\x123\n" +
	"\n" +
	"AddAddress\x12\x11.pb.AddAddressReq\x1a\x12.pb.AddAddressResp\x12<\n" +
	"\rUpdateAddress\x12\x14.pb.UpdateAddressReq\x1a\x15.pb.UpdateAddressResp\x12<\n" +
	"\rDeleteAddress\x12\x14.pb.DeleteAddressReq\x1a\x15.pb.DeleteAddressResp\x12H\n" +
	"\x11SetDefaultAddress\x12\x18.pb.SetDefaultAddressReq\x1a\x19.pb.SetDefaultAddressRespB\x1fZ\x1decommerce-demo/app/address/pbb\x06proto3"

var (
	file_app_address_pb_address_proto_rawDescOnce sync.Once
	file_app_address_pb_address_proto_rawDescData []byte
)

func file_app_address_pb_address_proto_rawDescGZIP() []byte {
	file_app_address_pb_address_proto_rawDescOnce.Do(func() {
		file_app_address_pb_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_address_pb_address_proto_rawDesc), len(file_app_address_pb_address_proto_rawDesc)))
	})
	return file_app_address_pb_address_proto_rawDescData
}

var file_app_address_pb_address_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_app_address_pb_address_proto_goTypes = []any{
	(*AddressItem)(nil),           // 0: pb.AddressItem
	(*GetAddressListReq)(nil),     // 1: pb.GetAddressListReq
	(*GetAddressListResp)(nil),    // 2: pb.GetAddressListResp
	(*AddAddressReq)(nil),         // 3: pb.AddAddressReq
	(*AddAddressResp)(nil),        // 4: pb.AddAddressResp
	(*UpdateAddressReq)(nil),      // 5: pb.UpdateAddressReq
	(*UpdateAddressResp)(nil),     // 6: pb.UpdateAddressResp
	(*DeleteAddressReq)(nil),      // 7: pb.DeleteAddressReq
	(*DeleteAddressResp)(nil),     // 8: pb.DeleteAddressResp
	(*SetDefaultAddressReq)(nil),  // 9: pb.SetDefaultAddressReq
	(*SetDefaultAddressResp)(nil), // 10: pb.SetDefaultAddressResp
}
var file_app_address_pb_address_proto_depIdxs = []int32{
	0,  // 0: pb.GetAddressListResp.addresses:type_name -> pb.AddressItem
	1,  // 1: pb.Address.GetAddressList:input_type -> pb.GetAddressListReq
	3,  // 2: pb.Address.AddAddress:input_type -> pb.AddAddressReq
	5,  // 3: pb.Address.UpdateAddress:input_type -> pb.UpdateAddressReq
	7,  // 4: pb.Address.DeleteAddress:input_type -> pb.DeleteAddressReq
	9,  // 5: pb.Address.SetDefaultAddress:input_type -> pb.SetDefaultAddressReq
	2,  // 6: pb.Address.GetAddressList:output_type -> pb.GetAddressListResp
	4,  // 7: pb.Address.AddAddress:output_type -> pb.AddAddressResp
	6,  // 8: pb.Address.UpdateAddress:output_type -> pb.UpdateAddressResp
	8,  // 9: pb.Address.DeleteAddress:output_type -> pb.DeleteAddressResp
	10, // 10: pb.Address.SetDefaultAddress:output_type -> pb.SetDefaultAddressResp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_app_address_pb_address_proto_init() }
func file_app_address_pb_address_proto_init() {
	if File_app_address_pb_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_address_pb_address_proto_rawDesc), len(file_app_address_pb_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_address_pb_address_proto_goTypes,
		DependencyIndexes: file_app_address_pb_address_proto_depIdxs,
		MessageInfos:      file_app_address_pb_address_proto_msgTypes,
	}.Build()
	File_app_address_pb_address_proto = out.File
	file_app_address_pb_address_proto_goTypes = nil
	file_app_address_pb_address_proto_depIdxs = nil
}
